### Promise

**特殊情况**

- prmoise参数不是函数
- 被当作函数直接调用
- onFulfilled和onRejected不是函数时, promise状态会继续向下传递
- 防止then返回的promise与resolvePromise的x引用相同
- 如果resolvePromise的x.then抛出异常，则以这个异常将promise拒绝
- 禁止resolvePromise的x.then重复调用



```js
'use strict';

var PENDING = 'pending';
var FULFILLED = 'fulfilled';
var REJECTED = 'rejected';

function MyPromise(excutor) {
  if (typeof excutor !== 'function') {
    throw new TypeError('Promise resolver ' + excutor + ' is not a function');
  }
  if (!(this instanceof MyPromise)) {
    throw new TypeError(this + ' is not promise');
  }
  var self = this;
  self.value = null;
  self.reason = null;
  self.status = PENDING;
  self.onFulfilled = [];
  self.onRejected = [];
  function resolve(value) {
    if (value instanceof MyPromise) { // promise实例
      return value.then(resolve, reject);
    }
    if (self.status === PENDING) {
      setTimeout(function() {
        if (self.status === PENDING) { //事件循环机制，解决同时调用resolve和reject可以触发两次状态更改
          self.value = value;
          self.status = FULFILLED;
          for (var i = 0; i < self.onFulfilled.length; i++) {
            self.onFulfilled[i](self.value);
          }
        }
      });
    }
  }
  function reject(reason) {
    setTimeout(function() {
      if (self.status === PENDING) {
        self.reason = reason;
        self.status = REJECTED;
        for (var i = 0; i < self.onRejected.length; i++) {
          self.onRejected[i](self.reason);
        }
      }
    });
  }
  try {
    excutor(resolve, reject);
  } catch (e) {
    reject(e);
  }
}
MyPromise.prototype.then = function(onFulfilled, onRejected) {
  onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : function(v) { return v };
  onRejected = typeof onRejected === 'function' ? onRejected : function(e) { throw e };
  var self = this;
  var promise = null;
  if (self.status === PENDING) {
    return promise = new MyPromise(function(resolve, reject) {
      self.onFulfilled.push(function (value) {
        try {
          var x = onFulfilled(value);
          resolvePromise(promise, x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
      self.onRejected.push(function (reason) {
        try {
          var x = onRejected(reason);
          resolvePromise(promise, x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    });
  } else if (self.status === FULFILLED) {
    return promise = new MyPromise(function (resolve, reject) {
      setTimeout(function () { // 按顺序执行promise，后面promise需要等待上一个promise状态更改才能执行
        try {
          var x = onFulfilled(self.value);
          resolvePromise(promise, x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    })
  } else if (self.status === REJECTED) {
    return promise = new MyPromise(function (resolve, reject) {
      setTimeout(function () {
        try {
          var x = onRejected(self.reason);
          resolvePromise(promise, x, resolve, reject);
        } catch (e) {
          reject(e);
        }
      });
    })
  }
}

MyPromise.prototype.catch = function (onRejected) {
  return this.then(null, onRejected);
}

// 返回一个Promise，在promise执行结束时，无论结果是fulfilled或者是rejected，在执行then()和catch()后，都会执行finally指定的回调函数
MyPromise.prototype.finally = function (fn) {
  return this.then(function (v) {
    setTimeout(fn);
    return v;
  }, function (e) {
    setTimeout(fn);
    throw e;
  })
}

  
function resolvePromise(promise, x, resolve, reject) {
  if (promise === x) { // 防止出现循环引用
    return reject(new TypeError('Chaining cycle detected for promise!'));
  }
  var thenCalledOrThrow = false; // 禁止调用多次
  if (x !== null && (typeof x === 'object' || typeof x === 'function')) {
    try {  // 如果x.then抛出异常，则以这个异常将promise拒绝
      var then = x.then;
      if (typeof then === 'function') {
        then.call(x, function (y) { // y仍有可能是PROMISE
          if (thenCalledOrThrow) {
            return;
          }
          thenCalledOrThrow = true;
          resolvePromise(promise, y, resolve, reject);
        }, function (error) {
          if (thenCalledOrThrow) {
            return;
          }
          thenCalledOrThrow = true;
          reject(error);
        })
      } else {
        resolve(x);
      }
    } catch (e) {
      if (thenCalledOrThrow) {
        return;
      }
      thenCalledOrThrow = true;
      reject(e);
    }
  } else {
    resolve(x);
  }
}


// 执行promises-aplus-tests测试, 请先执行npm i -g promises-aplus-tests
MyPromise.deferred = function() {
  let defer = {};
  defer.promise = new MyPromise((resolve, reject) => {
    defer.resolve = resolve;
    defer.reject = reject;
  });
  return defer;
}
try {
  module.exports = MyPromise
} catch (e) {}
```

```bash
npm i -g promises-aplus-tests
promises-aplus-tests core.js
```